# Generated by Django 5.1.3 on 2024-12-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial_created_at_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicesession',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ServiceSession',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
