# Generated by Django 5.1.3 on 2024-11-18 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_num', models.CharField(max_length=15, unique=True)),
                ('pwd', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('mypay_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aaf.user')),
                ('level', models.CharField(default='Standard', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aaf.user')),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_number', models.CharField(max_length=50, unique=True)),
                ('npwp', models.CharField(max_length=20, unique=True)),
                ('pic_url', models.URLField()),
                ('rate', models.FloatField(default=0.0)),
                ('total_finish_order', models.IntegerField(default=0)),
            ],
        ),
    ]
