# Generated by Django 5.1.3 on 2024-12-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
